name: Python Package Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        #python-version: ['3.5', '3.7', '3.8', '3.9', '3.10', '3.11', 'pypy2.7', 'pypy3.8']
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13', 'pypy2.7', 'pypy3.8']
        exclude:
          - os: macos-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.6'
          - os: ubuntu-latest
            python-version: '3.5'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: env PYTHONWARNINGS="ignore::DeprecationWarning" python -m pip install --upgrade pip
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: env PYTHONWARNINGS="ignore::DeprecationWarning" python -m pip install -r requirements.txt
      - name: Run Python tests
        run: python test_chi.py
      - name: Run Pure Python tests
        run: env NO_PYCRYPTO=true  python test_chi.py
